/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package addykorttipeligroupid.addykorttipeli.graafinenkayttoliittyma;

import addykorttipeligroupid.addykorttipeli.logiikka.Lukija;
import java.util.ArrayList;

/**
 *
 * @author ritakosk
 */
public class OhjeetRuutu extends javax.swing.JFrame {

    /**
     * Creates new form OhjeetRuutu
     */
    public OhjeetRuutu() {
        initComponents();
        aloitus();
    }
    
    private void aloitus(){
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }
    
    private void setTeksti() {
        Lukija lukija = new Lukija();
        ArrayList<String> ohjeetListana = lukija.haeOhjeet();
        String ohjeet = "<html>";
        for (int i = 0; i < ohjeetListana.size(); i++) {
            ohjeet += ohjeetListana.get(i);
            if (i < ohjeetListana.size()-1){
                ohjeet += "<br>";
            }
        }
        ohjeet += "</html>";
        jOhjeet.setText(ohjeet);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jOhjeet = new javax.swing.JLabel();
        jPalaa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(440, 450));
        setMinimumSize(new java.awt.Dimension(440, 450));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Ohjeet"));

        jOhjeet.setText("jLabel1");
        jOhjeet.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jOhjeet.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        setTeksti();

        jPalaa.setText("Palaa Aloitusruutuun");
        jPalaa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPalaaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jOhjeet, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPalaa)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jOhjeet, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPalaa))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPalaaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPalaaActionPerformed
        this.setVisible(false);
        AloitusRuutu.main(null);
    }//GEN-LAST:event_jPalaaActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jOhjeet;
    private javax.swing.JButton jPalaa;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
