/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package addykorttipeligroupid.addykorttipeli.graafinenkayttoliittyma;

import addykorttipeligroupid.addykorttipeli.logiikka.MuuLogiikka;

/**
 * Tämä luokka luo ruudun, josta näkee pelin loputtua, kuka pelaajista voitti pelin.
 * @author ritakosk
 */
public class VoittoRuutu extends javax.swing.JFrame {

    /**
     * Creates new form VoittoRuutu
     */
    public VoittoRuutu() {
        initComponents();
        aloitus();
    }

    private void aloitus() {
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }
    
    private String getVoittoTexti() {
        String voittoTeksti = MuuLogiikka.getVuoro().getPoyta().getTamanVuoronPelaaja().getNimi();
        voittoTeksti += " voitti pelin!";
        return voittoTeksti;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jVoittiPelin = new javax.swing.JLabel();
        jPalaaAloitusRuutuun = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jVoittiPelin.setText(getVoittoTexti());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jVoittiPelin, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jVoittiPelin)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPalaaAloitusRuutuun.setText("Palaa aloitus ruutuun.");
        jPalaaAloitusRuutuun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPalaaAloitusRuutuunActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPalaaAloitusRuutuun, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPalaaAloitusRuutuun)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPalaaAloitusRuutuunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPalaaAloitusRuutuunActionPerformed
        AloitusRuutu.main(null);
        this.setVisible(false);
    }//GEN-LAST:event_jPalaaAloitusRuutuunActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jPalaaAloitusRuutuun;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jVoittiPelin;
    // End of variables declaration//GEN-END:variables
}
