/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package graafinenkayttoliittyma;

import addykorttipeligroupid.addykorttipeli.logiikka.MuuLogiikka;
import java.awt.Component;

/**
 *
 * @author ritakosk
 */
public class VuoroRuutu extends javax.swing.JFrame {

    private boolean voikoLopettaa = false;

    /**
     * Creates new form VuoroRuutu
     */
    public VuoroRuutu() {
        initComponents();
    }

    private void joKolmeNostettu() {
        jNostitJoKolme.setVisible(true);
        voikoLopettaa = true;
        jEtOleNostanut3.setVisible(false);
    }

    private void etOleNostanutKolmea() {
        jEtOleNostanut3.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jPanel1 = new javax.swing.JPanel();
        jPelaa = new javax.swing.JButton();
        jNostaKortti = new javax.swing.JButton();
        jLopetaVuoro = new javax.swing.JButton();
        jLuovuta = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 38), new java.awt.Dimension(0, 38), new java.awt.Dimension(32767, 38));
        jLuovutaPeruuta = new javax.swing.JButton();
        jLuovutaOK = new javax.swing.JButton();
        jNostitJoKolme = new javax.swing.JLabel();
        jEtOleNostanut3 = new javax.swing.JLabel();

        jToggleButton1.setText("jToggleButton1");

        jToggleButton2.setText("jToggleButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPelaa.setText("Pelaa");

        jNostaKortti.setText("Nosta Kortti");
        jNostaKortti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNostaKorttiActionPerformed(evt);
            }
        });

        jLopetaVuoro.setText("Lopeta Vuoro");
        jLopetaVuoro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLopetaVuoroActionPerformed(evt);
            }
        });

        jLuovuta.setText("Luovuta?");
        jLuovuta.setInheritsPopupMenu(true);
        jLuovuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLuovutaActionPerformed(evt);
            }
        });

        jLuovutaPeruuta.setText("Peruuta");
        jLuovutaPeruuta.setVisible(false);
        jLuovutaPeruuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLuovutaPeruutaActionPerformed(evt);
            }
        });

        jLuovutaOK.setText("Luovuta");
        jLuovutaOK.setVisible(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPelaa, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jNostaKortti, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLopetaVuoro, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLuovutaPeruuta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 121, Short.MAX_VALUE)
                        .addComponent(jLuovuta))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLuovutaOK)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLopetaVuoro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPelaa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jNostaKortti, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLuovuta)
                            .addComponent(jLuovutaPeruuta))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLuovutaOK))))
        );

        jNostitJoKolme.setText("Nostit jo 3 korttia tällä vuorolla, et voi nostaa lisää kortteja.");
        jNostitJoKolme.setVisible(false);

        jEtOleNostanut3.setText("Et ole vielä nostanut kolmea korttia tällä vuorolla.");
        jEtOleNostanut3.setVisible(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jNostitJoKolme)
                            .addComponent(jEtOleNostanut3))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(252, Short.MAX_VALUE)
                .addComponent(jEtOleNostanut3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jNostitJoKolme)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLuovutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLuovutaActionPerformed
        jLuovuta.setVisible(false);
        jLuovutaOK.setVisible(true);
        jLuovutaPeruuta.setVisible(true);

    }//GEN-LAST:event_jLuovutaActionPerformed

    private void jLuovutaPeruutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLuovutaPeruutaActionPerformed
        jLuovuta.setVisible(true);
        jLuovutaOK.setVisible(false);
        jLuovutaPeruuta.setVisible(false);
    }//GEN-LAST:event_jLuovutaPeruutaActionPerformed

    private void jNostaKorttiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNostaKorttiActionPerformed
        if (MuuLogiikka.getVuoro().nostaKorttiGUI()) {
            joKolmeNostettu();
        }
    }//GEN-LAST:event_jNostaKorttiActionPerformed

    private void jLopetaVuoroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLopetaVuoroActionPerformed
        if (voikoLopettaa) {
            //lopeta vuoro
        } else {
            etOleNostanutKolmea();
        }
    }//GEN-LAST:event_jLopetaVuoroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VuoroRuutu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VuoroRuutu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VuoroRuutu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VuoroRuutu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VuoroRuutu vr = new VuoroRuutu();
                vr.setLocationRelativeTo(null);
                vr.setVisible(true);

            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel jEtOleNostanut3;
    private javax.swing.JButton jLopetaVuoro;
    private javax.swing.JButton jLuovuta;
    private javax.swing.JButton jLuovutaOK;
    private javax.swing.JButton jLuovutaPeruuta;
    private javax.swing.JButton jNostaKortti;
    private javax.swing.JLabel jNostitJoKolme;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jPelaa;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    // End of variables declaration//GEN-END:variables
}
